services:
  django:
    build: .
    container_name: django-app
    # depends_on:
    #   - scrapy-trip-dot-com-postgres-1
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DB_NAME=scrapydb
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=scrapy-trip-dot-com-postgres-1
      - DB_PORT=5432
    networks:
      - scrapy-trip-dot-com_scrapy-network
    # command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

networks:
  scrapy-trip-dot-com_scrapy-network:
    external: true