# Generated by Django 4.2.17 on 2024-12-31 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedtitledesc',
            name='hotel_id',
        ),
        migrations.RemoveField(
            model_name='summarytable',
            name='hotel_id',
        ),
        migrations.AddField(
            model_name='generatedtitledesc',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_data.hotel'),
        ),
        migrations.AddField(
            model_name='summarytable',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_data.hotel'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_id',
            field=models.IntegerField(unique=True),
        ),
    ]
