# Generated by Django 4.2.17 on 2024-12-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_data', '0002_remove_generatedtitledesc_hotel_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedtitledesc',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='summarytable',
            name='hotel',
        ),
        migrations.AddField(
            model_name='generatedtitledesc',
            name='hotel_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summarytable',
            name='hotel_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_id',
            field=models.IntegerField(),
        ),
    ]
